### boot配置文件 ###
spring:
   datasource:
      #name test
     url: jdbc:mysql://106.14.244.139:13306/psd?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT
     username: root
     password: 123456
#     url: jdbc:mysql://127.0.0.1:3306/psd?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT
#     username: root
#     password: root
     # 使用druid数据源
     type: com.alibaba.druid.pool.DruidDataSource
     driver-class-name: com.mysql.cj.jdbc.Driver


server:
  port: 8888
  max-http-header-size: 10240
  tomcat:
    uri-encoding: UTF-8
  # jsp热部署
  jsp-servlet:
    init-parameters:
      development: true

#mybatis
mybatis:
  type-aliases-package: com.lange.entity
  mapper-locations: classpath:mapper/*.xml
  configuration:
    # 缓存
    cache-enabled: false
    mapUnderscoreToCamelCase: true
#mappers
mapper:
  mappers: com.lange.utils.MyMapper
  not-empty: false
  identity: MYSQL

#pagehelper
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql